apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-policystore
  labels:
    usage: pv-policystore
spec:
  capacity:
    storage: {{ .Values.policymanagementapi.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /run/desktop/mnt/host/c/policymanagementapi
    type: ""