{{ if eq .Values.cloud_provider "baremetal" }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: glasswalltarget-pv
  labels:
    type: local
    usage: glasswalltarget-pv
spec:
  # storageClassName: azurefile
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/local/rancher/host/c/rebuild-data-out"
{{ end }}
---
{{ if eq .Values.cloud_provider "GCP" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glasswalltarget-pv
  labels:
    type: GCP-Filestore
    usage: glasswalltarget-pv
spec:
  #storageClassName: azurefile
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.gcp.filestore.target_path }}
    server: {{ .Values.gcp.filestore.target_ip_address }}
{{ end }}
