{{ if eq (lower .Values.cloud_provider)  "baremetal" }}
kind: PersistentVolume
apiVersion: v1
metadata:
  name: glasswallsource-pv
  labels:
    type: local
    usage: glasswallsource-pv
spec:
  #storageClassName: azurefile
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/local/rancher/host/c/rebuild-data-in"
{{ end }}
---
{{ if eq (lower .Values.cloud_provider) "gcp" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: glasswallsource-pv
  labels:
    type: GCP-Filestore
    usage: glasswallsource-pv
spec:
  #storageClassName: azurefile
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: {{ .Values.gcp.filestore.source_path }}
    server: {{ .Values.gcp.filestore.source_ip_address }}
{{ end }}