apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.podcontroller.rolename }}-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.podcontroller.saname  }}
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: {{ .Values.podcontroller.rolename }}
  apiGroup: rbac.authorization.k8s.io
