apiVersion: v1
kind: Service
metadata:
  name: ncfs-policy-update-service
  labels:
    app: {{ template "ncfs-policy-update-service.name" . }}
    chart: {{ template "ncfs-policy-update-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.ncfspolicyupdateservice.service.type }}
  selector:
    app: {{ template "ncfs-policy-update-service.name" . }}
  ports:
  - port: {{ .Values.ncfspolicyupdateservice.service.port }}
    targetPort:  {{ .Values.ncfspolicyupdateservice.service.port }}
    protocol: TCP
