apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-userstore
  labels:
    usage: pv-userstore
spec:
  capacity:
    storage: {{ .Values.identitymanagementservice.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/local/rancher/host/c/userstore
    type: ""