kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: identity-management-service-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "create", "get"] 