{{- if .Values.secrets }}
{{- if .Values.secrets.identitymanagementservice }}
{{- $root := . }}
{{- range $key, $value := .Values.secrets.identitymanagementservice}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $key }}
data:
  {{- range $subKey, $subValue  := $value }}
  {{ $subKey }}: {{ $subValue| b64enc }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
