image:
  registry: docker.io
  repository: yardenshoham/k8-rebuild-rest-api
  tag: latest

service:
  type: NodePort
  nodePort: 31344

resources:
  requests:
    cpu: 100m
  limits:
    cpu: 400m

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPU: 50
