apiVersion: v1
kind: Service
metadata:
  name: k8-rebuild-rest-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}