apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-policystore
  labels:
    usage: pv-policystore
spec:
  capacity:
    storage: {{ .Values.policymanagementapi.storage }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/local/rancher/host/c/policymanagementapi
    type: ""