apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: policy-management-api-rolebinding
subjects:
- kind: ServiceAccount
  name: policy-management-api-service-account
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: policy-management-api-role
  apiGroup: rbac.authorization.k8s.io 