# Defult settings to use with helm.
helmDefaults:
  timeout: 600

# The desired state of Helm releases.
releases:
- name: rabbitmq
  namespace: icap-adaptation
  labels:
    app: rabbitmq
  chart: ./rabbitmq
  version: 0.0.3
  missingFileHandler: Error
  values:
  - rabbitmqController:
      username: {{ requiredEnv "RABBITMQ_USERNAME" }}
      password: {{ requiredEnv "RABBITMQ_PASSWORD" }}

- name: ingress-nginx
  namespace: ingress-nginx
  labels:
    app: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  missingFileHandler: Error

- name: minio
  namespace: minio
  labels:
    app: minio
  chart: minio/minio
  missingFileHandler: Error
  values:
    - accessKey: {{ requiredEnv "MINIO_USERNAME" }}
      secretKey: {{ requiredEnv "MINIO_PASSWORD" }}
      buckets:
      - name: sourcefiles
        policy: none
        purge: false
      - name: cleanfiles
        policy: none
        purge: false
      fullnameOverride: minio-server
      persistence:
        enabled: false
      service:
        type: LoadBalancer

- name: glasswall-serivces
  namespace: icap-adaptation
  
  labels:
    app: services
  chart: ./services
  version: 0.0.3
  missingFileHandler: Error
  values:
  - minio:
      accessKey: {{ requiredEnv "MINIO_USERNAME" }}
      secretKey: {{ requiredEnv "MINIO_PASSWORD" }}
    cloud_provider: GCP
    gcp:
      filestore:
        source_ip_address: {{ requiredEnv "FILESTORE_IP" }}
        target_ip_address: {{ requiredEnv "FILESTORE_IP" }}
        transactions_ip_address: {{ requiredEnv "FILESTORE_IP" }}
        source_path: /{{ requiredEnv "FILESHARENAME" }}/source
        target_path: /{{ requiredEnv "FILESHARENAME" }}/target
        transactions_path: /{{ requiredEnv "FILESHARENAME" }}/transactions

- name: rebuild-api
  namespace: icap-adaptation
  chart: api
  values:
    - service:
        api:
          type: LoadBalancer
