apiVersion: v1
kind: Secret
data:
  password: {{ .Values.secrets.transactionqueryaggregator.transactionqueryserviceref.password }}
  username: {{ .Values.secrets.transactionqueryaggregator.transactionqueryserviceref.username }}
metadata:
  creationTimestamp: null
  name: transactionqueryserviceref
  namespace: management-ui
---
apiVersion: v1
data:
  password: {{ .Values.secrets.policymanagementapi.policyupdateserviceref.password }}
  username: {{ .Values.secrets.policymanagementapi.policyupdateserviceref.username }}
kind: Secret
metadata:
  creationTimestamp: null
  name: policyupdateserviceref
  namespace: management-ui
---
apiVersion: v1
data:
  password: {{ .Values.secrets.policymanagementapi.ncfspolicyupdateserviceref.password }}
  username: {{ .Values.secrets.policymanagementapi.ncfspolicyupdateserviceref.username }}
kind: Secret
metadata:
  creationTimestamp: null
  name: ncfspolicyupdateserviceref
  namespace: management-ui
---